---

- name: Install for ansible.builtin.apt_key
  ansible.builtin.apt:
    name: 
      - gpg
      - ca-certificates
      - curl
    state: present
    update_cache: yes
    install_recommends: yes

- name: set APT Key for Docker
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present

- name: Add Docker repository into sources list for debian 12
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64,arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian bookworm stable"
    state: present
    update_cache: True
  when: ansible_distribution_major_version == '12' 

- name: Install docker
  ansible.builtin.apt:
    name: 
      - docker-ce 
    state: present
    update_cache: yes
    install_recommends: yes