---

- name: set APT Key for Docker
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present

- name: Add Docker repository into sources list for Ubuntu 24
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64,arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu noble stable"
    state: present
    update_cache: True
  when: ansible_distribution_major_version == '24' 

- name: Install docker
  ansible.builtin.apt:
    name: 
      - docker-ce 
    state: present
    update_cache: yes
    install_recommends: yes
