---

- name: start ghosts dockers
  community.docker.docker_compose_v2:
    project_src: /opt/ghosts
    state: present
    wait: true
    wait_timeout: 120

- name: Wait until grafana API HTTP status is 200
  uri:
    url: 'http://localhost:3000/api/health'
    return_content: yes
    validate_certs: no
    status_code:
      - 200
  until: uri_output.status == 200
  retries: 24 # Retries for 24 * 5 seconds = 120 seconds = 2 minutes
  delay: 5 # Every 5 seconds
  register: uri_output

- name: Grafane Create postgres datasource
  community.grafana.grafana_datasource:
    grafana_url: "http://localhost:3000"
    grafana_user: "admin"
    grafana_password: "admin"
    name: "ghosts"
    ds_type: "postgres"
    ds_url: "ghosts-postgres:5432"
    database: "ghosts"
    user: "ghosts"
    sslmode: "disable"
    additional_json_data:
      postgresVersion: 12
      timescaledb: false
    additional_secure_json_data:
      password: 'scotty@1'

- name: Import Grafana dashboard 
  community.grafana.grafana_dashboard:
    grafana_url: "http://localhost:3000"
    grafana_user: "admin"
    grafana_password: "admin"
    state: present
    commit_message: Updated by ansible
    overwrite: true
    path: "/opt/ghosts/dashboard/{{item}}"
  loop:
    - 'GHOSTS-5-default-Grafana-dashboard.json'
    - 'GHOSTS-5-group-default-Grafana-dashboard.json'
    - 'GHOSTS-default-Grafana-dashboard.json'
    - 'GHOSTS-group-Grafana-dashboard.json'

- name: Touch /opt/ghosts/ghosts.finish
  ansible.builtin.file:
    path: /opt/ghosts/ghosts.finish
    state: touch
