---
# Install GHOSTS
# https://cmu-sei.github.io/GHOSTS/quickstart/
# 
# Check only Ubuntu 24 and Debian 12

- name: Install Ghosts
  ansible.builtin.include_tasks:
    file: ghosts.yml
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

